In [1]:
import numpy as np
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
array2=np.array([9,8,7,6,5])
array2

array([9, 8, 7, 6, 5])

In [7]:
array3=array1+array2
array3*10/2+1

array([51., 51., 51., 51., 51.])