In [1]:
import numpy as np
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
array2=np.array([9,8,7,6,5])
array2

array([9, 8, 7, 6, 5])

In [7]:
array3=array1+array2
array3*10/2+1

array([51., 51., 51., 51., 51.])

In [8]:
np.empty((10,))

array([5.49906130e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.74837101e-310, 8.01200449e+165, 1.16188862e+165, 5.25175929e-090,
       4.55998830e-037, 6.74841362e-310])

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0.5,10,0.5)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [11]:
np.linspace(-3,4)

array([-3.        , -2.85714286, -2.71428571, -2.57142857, -2.42857143,
       -2.28571429, -2.14285714, -2.        , -1.85714286, -1.71428571,
       -1.57142857, -1.42857143, -1.28571429, -1.14285714, -1.        ,
       -0.85714286, -0.71428571, -0.57142857, -0.42857143, -0.28571429,
       -0.14285714,  0.        ,  0.14285714,  0.28571429,  0.42857143,
        0.57142857,  0.71428571,  0.85714286,  1.        ,  1.14285714,
        1.28571429,  1.42857143,  1.57142857,  1.71428571,  1.85714286,
        2.        ,  2.14285714,  2.28571429,  2.42857143,  2.57142857,
        2.71428571,  2.85714286,  3.        ,  3.14285714,  3.28571429,
        3.42857143,  3.57142857,  3.71428571,  3.85714286,  4.        ])